### ISSUE TITLE
Object classification incorrect

### ISSUE THREAD

**Issue by dev-kamran2001** [Geekgineer/YOLOs-CPP#10]
I trained YOLOv11 on a custom dataset using Ultralytics in Python. The training results and detection using Ultralytics shows that the model doesn't have problem recognizing the classes of the objects it was trained for.

But after I export the PyTorch model to ONNX using Ultralytics export function and using the model with YOLOs-CPP, it loses the ability to properly classify objects (but still detects them). All detected objects has class ID of 0 (there's 0, 1 and 2).

During debugging I found out that line 833 of YOLO11.hpp the classConf never gets higher than objConf and since classId was initialized as 0 it remains 0.

I'm using the provided YOLO11 example for image recognition.
```
YOLO11Detector detector(modelPath, namesPath);
cv::Mat image = cv::imread(img);
std::vector<Detection> results = detector.detect(image);
```

The names file contains all the 3 class names properly.

The following is workflow information and library versions:
**ultralytics==8.3.49
torch==2.5.1
torchvision==0.20.1
onnxruntime (DLL)==1.20.1
onnxruntime (Python)==1.20.1
Microsoft Visual Studio 2022 v143
YOLOs-CPP latest version
[The Base YOLOv11 Model Used For Training](https://github.com/ultralytics/assets/releases/download/v8.3.0/yolo11n.pt)**

I can provide any extra information required but unfortunately I can't provide the trained model.

**Comment by Geekgineer** [comment]
Hi, thanks for pointing this out!


I pushed new change separating Object Confidence from Class Confidence: Modifed the loop to calculate the total confidence as the product of objConf and classConf:

```cpp
for (int c = 0; c < numClasses; ++c) {
    float classConf = ptr[(4 + c) * num_detections + d];
    float totalConf = objConf * classConf; // Combine objectness and class confidence
    if (totalConf > confThreshold && totalConf > maxConf) {
        maxConf = totalConf;
        classId = c;
    }
}
```

This ensures that both object confidence and class confidence contribute to the final decision.


Also, I just trained and exported a new model using the provided link. Then, I exported it again and made the inference; it works fine now!


![image](https://github.com/user-attachments/assets/5d9ebb86-13e2-49f8-8376-4080bf9f127e)

**Comment by Geekgineer** [comment]
Hi, please provide a screenshot from your ONNX exported file or similar custom Onyx model. The current pipeline worked fine for me with custom models.

https://netron.app/

![image](https://github.com/user-attachments/assets/f33ef95a-601b-4fbb-abc9-b29ccac35a8b)

**Comment by dev-kamran2001** [comment]
Here's the full screenshot
![best onnx](https://github.com/user-attachments/assets/daa68b3b-da02-4907-ba8f-f860a961fc41)

**Comment by Geekgineer** [comment]
Hi, to repduce the error I trained custom model Yolov11s for 3 classes for Paper Rock Scissors detection. 

I can confirm the cpp pipeline works fine for custom models.

Using the following [train-yolo11-object-detection-on-custom-dataset.ipynb](https://colab.research.google.com/github/roboflow-ai/notebooks/blob/main/notebooks/train-yolo11-object-detection-on-custom-dataset.ipynb)
![image](https://github.com/user-attachments/assets/e0e9123c-c27b-4230-92a1-f0361f09e5c5)
![image](https://github.com/user-attachments/assets/47aa34d8-7b66-4141-a8f0-99ef920b5cea)

ONNX model output:

![image](https://github.com/user-attachments/assets/7894c9a6-2094-47cb-a2af-3e67a1fdafe9)

I have attached the model for your reference. 
https://easyupload.io/kr5iy9

Regards,
