### ISSUE TITLE
Macos build error: /libonnxruntime.so needed by `image_inference'.  Stop.

### ISSUE THREAD

**Issue by sembiz** [Geekgineer/YOLOs-CPP#6]
Thank you for a great work!

Macos 15.1 build error:

No rule to make target  .../YOLOs-CPP/onnxruntime-osx-arm64-1.19.2/lib/libonnxruntime.so', needed by `image_inference'.  Stop.

When I renamed "libonnxruntime.dylib" file to "libonnxruntime.so" it was successfully builded.
But on ./run_video.sh there is another error:

GPU is not supported by your ONNXRuntime build. Fallback to CPU.
Inference device: CPU
libc++abi: terminating due to uncaught exception of type Ort::Exception: Load model from ../models/yolo11n.onnx failed:Fatal error: com.microsoft.nchwc:Conv(-1) is not a registered function/op
./run_video.sh: line 1:  3511 Abort trap: 6           ./video_inference

**Comment by sembiz** [comment]
Re-export of model through colab helped.
It works!

**Comment by Geekgineer** [comment]
Glad to hear that.
